export class PayslipDto {
    id: number;
    pay_year: string;
    pay_month: string;
    BP: string;
    NUMB: string;
    work_station: string | null;
    bpc: string | null;
    bpa: string | null;
    BPM: number;
    loan: number;
    ltenor: number;
    lbal: number | null;
    lmth: number;
    tpcoy: string;
    tpaddr: string | null;
    title: string;
    surname: string;
    othername: string;
    bankacnumber: string | null;
    bankname: string | null;
    gradelevel: string | null;
    gradetype: string | null;
    prvtaxtodate: number | null;
    taxtodate: number | null;
    grstodate: number | null;
    freetodate: number | null;
    txbltodate: number | null;
    currtax: number | null;
    netpay: number | null;
    groupcode: string | null;
    factory: string | null;
    location: string | null;
    nsitf: string | null;
    nsitfcode: string | null;
    email: string | null;
    status: number;
    payclass: string;
  }
  